# Inlets Client Configuration
# Generated by Terraform on ${timestamp()}
#
# This file contains sensitive information - do not commit to version control
# Add .env.inlets to your .gitignore

INLETS_REMOTE=wss://${domain_name}:8123
INLETS_TOKEN=${inlets_token}
INLETS_UPSTREAM=${upstream}